# Site Settings

title: Varun
subtitle: tronics
email: varunbhat@geektronics.in
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _varunbhat
github_username:  varunbhat
facebook_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
instagram_url: https://instagram.com

## Homepage tiles
#tiles-source: posts # accepts "posts" or "pages"
#tiles-count: 6

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

include: ['_pages']

sass:
style: compressed




