# Site Settings

title: Varun Bhat
subtitle: Programmer Unleashed
email: varunbhat.kn@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _varunbhat
github_username:  varunbhat
linkedin_url: https://www.linkedin.com/in/varunbhatkn

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock


include:
  - _pages
  - _sass

sass:
  sass_dir: _sass
  style: compressed
